main: com.letsgoaway.legacyconsole.LegacyConsole
name: LegacyConsole
version: 1.0
depend: [ProtocolLib]
softdepend: ["Multiverse-Core"]
commands:
  hub:
    description: Go to the hub.
    usage: /<command>
