main: com.letsgoaway.legacyconsole.LegacyConsole
name: LegacyConsole
version: 1.0
api-version: 1.14
depend: [ProtocolLib]
softdepend: ["Multiverse-Core"]
commands:
  hub:
    description: Go to the hub.
    usage: /<command>
  setRPProxy:
    description: Sets the proxy for resource pack downloading
    usage: /<command>
